---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1588530/public_html/tmf_production/
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R gambar $DEPLOYPATH
    - /bin/cp -R google $DEPLOYPATH
    - /bin/cp -R halaman $DEPLOYPATH
    - /bin/cp -R login $DEPLOYPATH
    - /bin/cp -R view $DEPLOYPATH
    - /bin/cp dashboard.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp recovery_password.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
